name: Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: ["main"]
  push:
    branches: ["main"]
  schedule:
    # run test automatically every month on th 4th at 3
    - cron: "0 3 4 * *"

defaults:
  run:
    shell: bash -el {0}

jobs:
  tests:
    name: Tests (${{ matrix.python_version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", # "macos-latest", "windows-latest"
             ]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

  steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
    - name: Install
      run: |
        python -m pip install -e .\[test\]
    - name: List versions
      run: |
        conda list
        python -c "import asyncmd; print('asyncmd version is: ', asyncmd.__about__.__version__)"
    - name: Unit tests
      run: pytest -vv --cov=asyncmd --cov-report=term-missing
